### ISSUE TITLE
Buildings with wall kits placed

### ISSUE THREAD

**Issue by R3DSTARMAN** [42MonthsAfter/42MonthsAfter-Prod#113]
finding many buildings with these wall kits placed on roofs. 
![image](https://user-images.githubusercontent.com/84424222/129282520-669d6025-f41a-4a12-bf9b-c3f0cd2ecacb.png)

**Comment by RyLickliter** [comment]
So this is related to one of the mods (basebuilding+, builderitems, MSP) having an unsupported line of code in their mod. Other servers are reporting it too. I've detailed it in reports to the mod creators, we are just waiting on a fix. 

This messes with vanilla placements too for garden plots. just a heads up.
