### ISSUE TITLE
Bed Despawning?

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#167]
Cass had mentioned that a small bed had despawned, I don't know much detail about it, could reach out to them.

@SargeD You mentioned that some of the items being removed. Could this be part of it?

**Comment by SargeD** [comment]
Yeah, the bed was one of the new items in the role play mod. It despawned for him around the same time we had the military boxes from that same mod despawn. Should be fixed now.
