### ISSUE TITLE
Admin Hatchet Not Working

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#170]
Turns out one of the mods broke the admin hatchet. It still works in that you don't have to have the supplies but it takes about 5 minutes to finish each stage of construction.

**Comment by RyLickliter** [comment]
Reported to the mod creator

**Comment by SargeD** [comment]
Is that what is "broke"? The time is longer? We noticed that with building in general, all build time seem to have been extended
