### ISSUE TITLE
Cannot sell anything at trader

### ISSUE THREAD

**Issue by R3DSTARMAN** [42MonthsAfter/42MonthsAfter-Prod#174]
Nothing shows as sellable. When I look at everything in my inventory while in the trader window everything shows as no value. All All of the different traders have the same results.

**Comment by SargeD** [comment]
That changed when the updated trader plus the last time, don't touch your side of the screen, scroll through on the trader side and your side will switch as well.

**Comment by RyLickliter** [comment]
@R3DSTARMAN You good? Can we close this out?

**Comment by R3DSTARMAN** [comment]
I’m good yes, thanks. Feel free to close.
