### ISSUE TITLE
Add Air Drop Mod

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#209]
We don't have to go with the one that had on v10, but no matter what we need to customize the drop areas for the new map.

**Comment by RyLickliter** [comment]
@Raider2-1 You mentioned Air Raids but didn't see air drops anywhere. Do we want to keep these?

Feel like it would be a cool way to add higher tier items in full (weapon + mags + ammo) to public events.

What do you think?

**Comment by Raider2-1** [comment]
I think that Air Drops could stay.
If they do, I think that they should only have T3 building supplies, NBC equipment, NVGs, and the top tier guns. However, they should be spaced out a ton. 
If I'm working on the Hummers, I'll mess with Air Drops too with their loot tables
Sound alright?
