### ISSUE TITLE
Remove all <1000 Hummers from the types file

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#226]
Hummers will be for factions only and we will have only color variants that match the colors of the factions.

Right now we are looking at black / black camo for Faction 1 and OD green / green camo for Faction 2.

We need to remove all the other variants for similpicty, including in the types.xml, trader vehicle menu, and the community online tools vehicle settings.

**Comment by Raider2-1** [comment]
I can do this most likely

**Comment by Raider2-1** [comment]
Quick Clarification, I know all other variants need to go but for the Black and Green, what size/s needs to stay? @RyLickliter

**Comment by RyLickliter** [comment]
As the title says, anything not the 1000 capacity. ha

**Comment by RyLickliter** [comment]
@Raider2-1 What would you think about extending the scope of this ticket to include:

1. removing them from the auto trader at the QuickStop
2. Adding the 1000 black models to the RLF faction trader and the green models to the Remnants trader?

Can use the same prices from the current trader file to make things easier.
