### ISSUE TITLE
Add Prison Fence to the Boundary of Map

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#227]
You can run past the edge of the map today, we need a way to block that off.  Purposed fix would be to add the prison wall along the entire boarder of the map keeping everyone inside.

Will need to check what this does for performance. If we use a single fence type we should be okay, but want to make sure we aren't killing performance after @SargeD has spent a ton of time building it out.

**Comment by RyLickliter** [comment]
Saw the first section! Looks great! Didn't see any performance issues but it's so much land that it makes me nervous. ha

**Comment by SargeD** [comment]
Done!
