### ISSUE TITLE
Discord Bot Needed for Auto Assigning Factions

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Prod#228]
Would be great to set up Discord so when new players join they are automatically added to the right free folk channels. 

Would be awesome if this could be used for picking factions as well.

If we can make it work with whitelisting the server, that would be awesome too. Think we will need to gather their 44 character steam ID so I can assign them to a faction to make sure they get the right gear + access to the faction channels.

We will need a solution for the int.c for assigning the right gear, this will be dependent on it.

**Comment by HoneyBrear** [comment]
You CAN have a discord bot give everyone the Free Folk role on accept a rules page or something then have them removed when they are set to a faction manually.
We can't auto assign via discord as we can't pull connected accounts via bots(they dont allow you) So having a bot with a request command and a staff to manually set them has always been the only way.
