### ISSUE TITLE
Add Armband Mod

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#232]
There is a super light armband mod that we could add to give the free folk more ways of grouping up and identifying each other.

Steam link: https://steamcommunity.com/sharedfiles/filedetails/?id=1627811046&searchtext=armband

Could also optimize our own by reskinning?

**Comment by HoneyBrear** [comment]
We could just reskin a few into the servermod instead of a separate mod, better optimize if we are only doing a few and dont want all the country armbands.
