### ISSUE TITLE
Update the MVS Gear Storage Capacity

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#234]
Want to make the value of the faction gear be really high by improving the carrying capacity on the MVS faction gear.

Each faction memeber will start with the same intro / lower level mvs gear and have the option to purchase upgraded faction gear from their faction trader at their HQ.

Would like to level it so there are several different tiers capacity and price wise.

Need to do a full breakdown of the items, their purposed capacity and their higher pricing.

**Comment by HoneyBrear** [comment]
Here is the current breakdown for storage capacity
Heavy combat vest = zero storage
Combat vest = zero storage
Chestrigs = {7,5};
MVS_Magazine_Pouch =  {6,4};
MVS_Molle_Panel = {6,4};
MVS_Taco_Pouch = {6,4};
MVS_Admin_Pouch = {3,4};
MVS_Heavy_Pouch = {6,5};
MVS_Utility_Pouch = {1,3};
MVS_Medical_Pouch = {2,4};
MVS_Assault_Pack = {8,10};
MVS_Sling_Pack = {8,10};
MVS_Compact = {5,10};
MVS_Rucksack = {10,12};
MVS_Pack = {8,10};
Armor_Rack = {10,12};
MVS_CombatPants = {6,5};
MVS_CombatShirt = {6,5};
MVS_GorkaPants = {6,5};
MVS_GorkaJacket = {7,6};
MVS_Pants_BDU = {6,4};
MVS_Shirt_BDU = {6,5};
MVS_Radio_Pack = {6,4};

**Comment by RyLickliter** [comment]
At least in the beginning I was thinking that we would split up the gear itself and vary the sizes between them. 

Like say we have 5 backpacks, instead of having multiple size variants (like 1 in 3 different sizes) we could say backpack 1 is stock size (this is what you get when you spawn in), backpack 2 is +60 slots., backpack 3 is +80, etc.

This way you can identify the size count / tier by the pack itself. 

Could do the same with helmets and chest rigs for protection. What do you think? @Raider2-1 @SargeD  Thoughts?

**Comment by HoneyBrear** [comment]
Default bags
MVS_Assault_Pack = {8,10}; physical size {5,7}; quickBarBonus = 2;
MVS_Sling_Pack = {8,10}; physical size  {5,7}; quickBarBonus = 2;
MVS_Compact = {5,10}; physical size {5,7}; quickBarBonus = 2;
MVS_Rucksack = {10,12}; physical size {7,8}; quickBarBonus = 2;
MVS_Pack = {8,10}; physical size {5,7} quickBarBonus = 2;

Physical size being how much space they take up in cargo and quickbar bonus is how many extra quickbar squares they gives.
