### ISSUE TITLE
Faction Trader

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Prod#248]
MVS Multicam Tropic BDU Pants are missing from The Remnants Faction Trader
Also, its probably intentional but theres supply differences in the traders
Ex. PLF sells ghillies but doesnt have a blueprint, while the TR has the opposite. Just thought to mention that

**Comment by RyLickliter** [comment]
The items in it are from me testing different things.  The way they are set up is like this:

Public Trader:
Only accepts weapons, ammo, mags and medical supplies (purchases for 20% increase in price from the QuickStop). Only items that have been sold to it will be available.

Anyone can sell and purchase these items from this public trader. (Sell prices are the same as the QuickStop)

Factions will have to purchase items from this trader at full price until we figure something out.

Faction Trader + Storage:
Faction specific gear can only be purchased from here and will have unlimited stock, this includes cars.

All other items will be considered "storage" meaning faction members can sell items here for $1 and purchased back for $1. Only items sold will be available. This is to help with performance by not having to keep these items in game storage.

The only items that CAN NOT be stored are weapons of any kind and cash. This is to make it so there is still a reason to raid a HQ. 

This isn't a perfect solution, but an interesting test. What do you think?

**Comment by SargeD** [comment]
I did notice a few items missing from our trader, just OD or Mulitcam variants
