### ISSUE TITLE
RLF Traders

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Prod#268]
![image](https://user-images.githubusercontent.com/83690102/142977890-1470777f-0202-475e-b49a-0c86ea299506.png)

The public trader is just chillin outside his box

![image](https://user-images.githubusercontent.com/83690102/142977923-22ce3d13-aca9-40dc-ba41-81ad9b0cabe2.png)

Im sure this guy will end up getting a spot but he's in the courtyard for now

**Comment by RyLickliter** [comment]
Updated!!
