### ISSUE TITLE
Make Armbands Unlimited stock at Trader

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#276]
Need to set armbands to be unlimited and always available at the QuickStop so groups can access them easily

**Comment by SargeD** [comment]
So, I fixed this, pushed it to the previously created branch "TraderPlusPriceConfig" but it never gave me an option to make a pull request. Is this because there was one already in for this branch??

**Comment by RyLickliter** [comment]
Should!
