### ISSUE TITLE
Add City Names to the Map

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#287]
We can edit the VPP config file` VPPMapConfig.json` by adding the following entry for each major location:

> `
>         {
>             "M_MARKER_NAME": "CITY NAME",
>             "M_ICON_PATH": "VanillaPPMap\\GUI\\Textures\\CustomMapIcons\\waypointeditor_CA.paa",
>             "M_COLOR": [
>                 255.0,
>                 255.0,
>                 255.0
>             ],
>             "M_POSITION": [
>                 REPLACE WITH X COORDINATE,
>                 REPLACE WITH Y COORDINATE,
>                 REPLACE WITH Z COORDINATE
>             ],
>             "M_ISACTIVE": 1,
>             "M_IS_3D_ACTIVE": 0
>         },`

Need to make sure 3D active is set to 0 so it only shows up on the map view, not in the world.

**Comment by RyLickliter** [comment]
Can follow the format from the file with Hunter Cabin or QuickStop.

**Comment by SargeD** [comment]
Do you have more to add?
