### ISSUE TITLE
Border Fence Not Meeting Ground

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/42MonthsAfter-Prod#301]
![20211204132239_1](https://user-images.githubusercontent.com/8458331/144757020-ca33b990-6c86-4784-995e-461a87869368.jpg)

**Comment by RyLickliter** [comment]
@SargeD Saw this when out exploring / testing.

**Comment by SargeD** [comment]
What the hell happened there?
 I'll check it out

**Comment by SargeD** [comment]
This should be fixed
