### ISSUE TITLE
Car despawning while driving?

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Prod#312]
Had another incident similar to this 
"Literally dont know how to explain this but here goes
We were driving around the area of Camp Eagle when we experienced some major desync. I couldnt do anything in my vehicle and I wasnt in the same spot that my teammates saw me in, so i relogged
Came back, spawned away from where both i "was" and where my teammates could see me. We retraced my entire route multiple times and literally my vehicle disappeared while i was driving it"
This was on Deer Isle 
Now something similar has happened to me again, this time with a RUS pickup truck. Sarge saw me stop, i was 100m forwards, still in control. I was given ping notifications and i relogged. When I came back in, i was 200m behind where Sarge was. Ran up, no vehicle anywhere. 
Bunker said he might of found it underwater. 

Sarge POV 
![image](https://user-images.githubusercontent.com/83690102/144956452-d3189f45-ac45-4143-994a-d3921a671ca6.png)

Mine 
![image](https://user-images.githubusercontent.com/83690102/144956901-00afe0d3-1dcb-4eb7-8abe-fe86226221e2.png)

After relogging, Sarge could not see the car

**Comment by BnYrB** [comment]
We believe this to be a map issue, closing as we are changing back to Deer Isle
