### ISSUE TITLE
Vehicle Parts

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Prod#314]
There are a few vehicles that spawn in when bought, without all the tires.

**Comment by RyLickliter** [comment]
Do you know which ones?

**Comment by SargeD** [comment]
Neither of the M3S (Truck_Covered) are in the config, and they spawn in as soon as they are bought

The Sarka (Sedan_02)
No Trunk
No Hood
Two wrong color doors

The Red Sarka (Sedan_02_Red)
No hood
No Trunk
Two wrong doors

The Grey Sarka (Sedan_02_Grey)
No Hood
No Trunk
Two wrong doors

The Blue Ada (OffroadHatchback_Blue)
No Spare Tire
Wrong Trunk
Wrong Hood
Wrong Doors

The Blue Ada (OffroadHatchback_White)
No Spare Tire
Wrong Trunk
Wrong Hood
Wrong Doors

The Blue Gunter (Hatchback_02_Blue)
Wrong Hood
Wrong Trunk
Wrong Doors

The Blue Gunter (Hatchback_02_Black)
Wrong Hood
Wrong Trunk
Wrong Doors

The Black Olga (CivilianSedan_Black)
Wrong Trunk
Wrong Hood
Wrong Doors

The Black Olga (CivilianSedan_Wine)
Wrong Trunk
Wrong Hood
Wrong Doors

**Comment by SargeD** [comment]
Im knocking this out right now
