### ISSUE TITLE
Vehicle Death

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Prod#323]
Second instance of this happening, driving normally, sudden spike, camera flies, car is dead. There aren't and obstacles or anything. 
![image](https://user-images.githubusercontent.com/83690102/145724491-1e3f0433-83c8-495f-a43c-02ea512eef31.png)

**Comment by RyLickliter** [comment]
Closing as we have a temp fix in place with No Vehicle Damange
