### ISSUE TITLE
Update Airdrop + KotH Loadouts...

### ISSUE THREAD

**Issue by BnYrB** [42MonthsAfter/42MonthsAfter-Prod#325]
We should add a bunch of different load outs to the payout for Airdrops and King of the Hills. 

We should also think about swapping the hardigg on the KotHs for a wooden create to keep the value of hardiggs up.

**Comment by RyLickliter** [comment]
@Raider2-1 Is this what you were saying you're interested in taking on over break?

**Comment by BnYrB** [comment]
Updated for new map
