### ISSUE TITLE
Rus Vehicle GAZ-33081

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Prod#327]
This may be an issue with other vehicles within the mod. The first wooden crate slot on the vehicle will not accept a wooden crate, hardigg, military crate or other like containers.

**Comment by BnYrB** [comment]
![Screenshot 2021-12-15 183900](https://user-images.githubusercontent.com/8458331/146281701-9a6651d5-ef9c-414e-bf41-f15b24e17479.png)

Reported to the mod creator

**Comment by BnYrB** [comment]
Removing this mod per communities request
