### ISSUE TITLE
TWP Weapons

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Prod#329]
It looks like a lot of the TWP weapons are flagged 
<flags count_in_cargo="1" count_in_hoarder="1" count_in_map="1" count_in_player="1" crafted="0" deloot="0" />

**Comment by RyLickliter** [comment]
I don't know what flagged is in reference to. Whats going on exactly?

**Comment by SargeD** [comment]
![image](https://user-images.githubusercontent.com/36716178/146086408-7c3c204e-e228-4873-a54b-92efad610cb0.png)
The Types file

**Comment by BnYrB** [comment]
ahhh got you. ok, can make this update. There shouldn't be anything that is counting on person
