### ISSUE TITLE
tamed dogs despawn 

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/42MonthsAfter-Prod#346]
had a dog i tamed with some bones i had told him to stay in my room in the faction base then logged for the night when i came back he was gone and i couldnt call him back to me

**Comment by BnYrB** [comment]
Did you have a dog house by chance?

**Comment by Joshuabab** [comment]
no i didnt

**Comment by BnYrB** [comment]
Removing this mod as it is broken
