### ISSUE TITLE
Test server notes

### ISSUE THREAD

**Issue by Sharkparty65** [42MonthsAfter/42MonthsAfter-Prod#366]
1. Military zombies do not respond to grenades. Also tried shooting gas pumps and they don't take damage from that either. Seems like they take no explosive damage whatsoever.
2. Could probably turn down the military backpack spawn rate a tad. Seeing a LOT of bags and rifle holsters
3. The Walther Gewehr 43 rifle and corresponding magazines are a little bugged. They don't often show up in the "vicinity" section of the inventory screen, and the prompt to pick them up sometimes shows up in the corner of the screen, not next to the item. It works fine after I pick it up, but it's a little tricky when they're on the ground
4. AI at Old Town pointed their weapons at me when they saw me but didn't start shooting until I aimed back. I didn't see them reload but they all had semi-auto weapons and were firing pretty slowly.
5. I saw that you added the virus mod, awesome! One thing to note, it works best if the spawn rate for (empty) syringes is set high and the vials very rare, to incentivize having to craft the cure, or having to go to dangerous areas to find the vials.
6. There is no server restart message

I'll add more as I go along.

**Comment by BnYrB** [comment]
1. The military zombies and grenades has been updated which should fix the gas pump issue too.

2. Will do, good feedback.

3. Not much we can do about this one, a mod issue that we can't update. If it's unusable we should remove it from the loot table.

4. AI will point their weapons if you are holding a gun, but will only shoot when you raise your weapon. The reload issue should be resolved as well.

5. Will do, appreciate the suggestions!

6. There won't be until we go full live, part of our GameLabs features.
