### ISSUE TITLE
What I Experienced

### ISSUE THREAD

**Issue by ShadowMan101st** [42MonthsAfter/42MonthsAfter-Prod#367]
Good Afternoon, I just wanted to elaborate on some things that I endured today playing on the test server. (1) The makeshift shelters, are awesome! crafted a few during my game play. (2) 9AM crash, or maybe a restart, I don't know. (3) AI is not functioning correctly, to my eyes. Example: I heard shots at the air field, and by the time I got over there the zombies were kicking the crap out of the AI, and eventually killed 1 AI member, I didn't see any other AI. I killed the remaining zombies and grabbed the AK with a magazine, but no ammo off the AI. I ended up dying to the sickness, and respawning at another location I'll get to that in a minute. After respawning to a different location I saw the zombies attacking another AI member, and eventually killing him. I didn't hear any shots, and was only a single AI member. Getting back to the sickness, I was unable to find any Tetra, and two of the hospitals I went to, or any in the world. I got sick twice, but the server crashed, or restarted at 10AM, but I probably would of died because, I was sick again. Overall, I'm liking the balance in the loot, and more medicine may need to be buffed to combat the sickness, I understand Zombies making you bleed will have that effect, but on this particular run, I had zero luck finding medicine. Well, that's it for now hope this helps. Great job on the server. You can always watch the first two hours of my stream to watch first hand what I saw and witnessed.   
https://www.twitch.tv/shadowman101st

**Comment by BnYrB** [comment]
1. Great! There are a lot of fun ways to camp on the go, personally a fan of the medium tent and some of the bags that they fit on

2. Was a restart! There were no alerts as it was on a dev server than GameLabs wasn't hooked up to.

3. Zombies and AI will fight. AI has unlimited mags to fight them off until they are killed, or their weapons jam and they get killed or they fend them all off. They won't shoot at you until you raise your weapon at them. 

4. We have upp'd the med and put cure and cure components in at higher numbers. But still might have to stay dry and not fight any Zs until you've found some stuff to take care of the illness ha

**Comment by ShadowMan101st** [comment]
Awesome! Thanks, for clarifying. Can't wait to check it out.
