### ISSUE TITLE
Quickstop zombies

### ISSUE THREAD

**Issue by Sharkparty65** [42MonthsAfter/42MonthsAfter-Prod#376]
Not sure if this is an effect of being near Quickstop but the zombies near the trader zone are weirdly hard to kill.

**Comment by Raider2-1** [comment]
Military, police and some other zombie types are extremely tough, soaking up damage like no other. Headshots are pretty much required, it's intentional.

**Comment by BnYrB** [comment]
We can probably tone it down a bit though given the head boxes. Should look to remove this apawn location anyway

**Comment by GameTimeOperator** [comment]
@BnYrB in the two videos I posted even headshots against unarmored zeds seem like they dont faze them

**Comment by BnYrB** [comment]
This is because they are police as stated. They are tougher than most.

While we can't do anything about the hitboxes, we have made adjustments to the headshot tolerance which should make them go down easier. Again, won't be perfect but we are limited inwhat we can control.
