### ISSUE TITLE
Not fully loading

### ISSUE THREAD

**Issue by Kronix0643** [42MonthsAfter/42MonthsAfter-Prod#377]
Tried logging into the game. Got in but only had stamina bar and needs bars showed up. Pressed escape and it disconnects me from server. Tried re-logging numerous times

**Comment by SargeD** [comment]
Next time hit the tilde key ( ~ ), to the left of the 1 key. That hides and shows your bars. If you log in and you have the arrow cursor, hit LAlt + Enter, that changes from full screen to windowed mode. That will fix the issue of the cursor.

**Comment by BnYrB** [comment]
I get this a lot too, it's just the game I think. ha I just relog and that tends to solve the issue.
