### ISSUE TITLE
Zombie hit reg?

### ISSUE THREAD

**Issue by GameTimeOperator** [42MonthsAfter/42MonthsAfter-Prod#381]
https://www.youtube.com/watch?v=rIvEja4XXR4 - part 1
https://www.youtube.com/watch?v=0XpWlp11fa0 -part 2

**Comment by BnYrB** [comment]
There isn't anything we can do about the hit zones themselves, but we can adjust the resistance to headshot criteria. 

Have set it to 0 from 0.1, should result in instant death if in the hit box and the zombie isn't wearing a helmet. 

Again, limited control in what we can do here.

Updates will go in at the midnight restart tonight.
