### ISSUE TITLE
backpack carrier rig damaged after logging off

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/42MonthsAfter-Prod#382]
so logged off yesterday with my carrier rig and it was still pristine but when i logged back in it was ruined and it gave me a message about stuff from my inventory being dropped due to not having space and my backpack and drybag were on the ground.

**Comment by Joshuabab** [comment]
my pkp also despawned off the top of the hardig

**Comment by BnYrB** [comment]
Friendly ping!

**Comment by Joshuabab** [comment]
sorry yeah i was in base when i logged got shot a bit before but it didn't say it was ruined when i checked it after the firefight was probably just desynced dayz being dayz

**Comment by BnYrB** [comment]
ok, well let me know if this happens again and we will open another ticket to look into it.
