### ISSUE TITLE
airdrop location

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/42MonthsAfter-Prod#384]
just had an airdrop say it was dropping near Novy sobor I'm pretty sure that's a chernarus spot and it dropped dead center of the map

**Comment by BnYrB** [comment]
Better get in that raft and start heading that way... Going to be a long sale.

Will get it removed from the list!

**Comment by Sharkparty65** [comment]
Saw this too but it said Krasnostav and the airdrop showed up on the map in the ocean near that unfinished snow area in the northeast corner of the map

**Comment by BnYrB** [comment]
Updated, will go into world in the midniight restart.
