### ISSUE TITLE
Possible barrel bug

### ISSUE THREAD

**Issue by Sharkparty65** [42MonthsAfter/42MonthsAfter-Prod#385]
It seems like every barrel we find ends up filling with water and everything we put in it gets wet regardless of where we put it or we keep it closed.

**Comment by BnYrB** [comment]
are they filling up when it rains?
 It may have had water in it, which I think you can empty with a canteen but I'm not sure, will start testing this.

**Comment by BnYrB** [comment]
Friendly ping

**Comment by BnYrB** [comment]
If there were found and they were open there is a chance they may have had water in them already. I have a couple test barrels out and can't replicate this issue. Will continue to monitor it though.
