### ISSUE TITLE
Loot Suggestions from some players

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/42MonthsAfter-Prod#405]
I was talking with a couple players last night at they brought up some points. They said they had been playing from about 20 hours and hadn't found any nails. I too have only found a couple boxes over the two weeks since launch and I found those in the very beginning. They were going to be leaving the server due to not being able to secure any of there stuff. They had also said they felt there were too many weapons and not enough other items such as, sewing kits, wetstones, tools in general.

Maybe we should start looking at tweaking some of the numbers now that DeerIsle has been up and running smoothly for almost two weeks now.

**Comment by BnYrB** [comment]
I doubled the nominals on nails and wire, its going in at the midnight restart tonight.

Also increased the minimum and removed the coast and firehouse as places they can be found
