### ISSUE TITLE
Repair items

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/42MonthsAfter-Prod#451]
Items like the sewing kit and the epoxy putty only give a 1/100 item instead of a 100/100 item

**Comment by BnYrB** [comment]
Is this when you bought them? Or when you found them?

**Comment by Raider2-1** [comment]
Sorry, thought I had specified. It happens when bought from the trader

**Comment by BnYrB** [comment]
All good! Should be fixed at the next update
